---
- name: Install GRUB theme
  hosts: all
  become: true
  tasks:
    - name: Create hyperfluent directory
      ansible.builtin.file:
        path: /boot/grub/themes/hyperfluent
        state: directory
        mode: "0755"
    - name: Extract tar.gz file
      ansible.builtin.unarchive:
        src: ../other/hyperfluent-arch.tar.gz
        dest: /boot/grub/themes/hyperfluent
    - name: Comment out existing GRUB_THEME lines
      ansible.builtin.replace:
        path: /etc/default/grub
        regexp: "(GRUB_THEME=)"
        replace: "#GRUB_THEME="
    - name: Add theme to GRUB config
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_THEME=".*"'
        line: 'GRUB_THEME="/boot/grub/themes/hyperfluent/hyperfluent.theme"'
        insertafter: EOF
    - name: Update GRUB
      ansible.builtin.command:
        cmd: grub-mkconfig -o /boot/grub/grub.cfg
      changed_when: false
