---
- name: Install packages
  hosts: all
  become: true
  tasks:
    - name: Install packages
      yay:
        name: "{{ item.name }}"
        state: present
        update_cache: true
      loop: "{{ packages }}"
      when: item.install

    - name: Copy config files for each package
      ansible.builtin.copy:
        src: "{{ item.1.src }}"
        dest: "{{ item.1.dest }}"
        mode: "{{ item.1.mode }}"
        owner: "{{ item.1.owner | default(user) }}"
        group: "{{ item.1.group | default(user) }}"
      loop: "{{ packages | subelements('configs') }}"
