---
- name: Setup NVIDIA BETA drivers (DKMS)
  hosts: all
  become: true
  tasks:
    - name: Check if nvidia-beta-dkms is installed
      ansible.builtin.command:
        cmd: /usr/bin/pacman -Q nvidia-beta-dkms
      changed_when: false
      register: nvidia_beta_dkms
      ignore_errors: true
    - name: Check if nvidia-utils-beta is installed
      ansible.builtin.command:
        cmd: /usr/bin/pacman -Q nvidia-utils-beta
      changed_when: false
      register: nvidia_utils_beta
      ignore_errors: true
    - name: Check if lib32-nvidia-utils-beta is installed
      ansible.builtin.command:
        cmd: /usr/bin/pacman -Q lib32-nvidia-utils-beta
      changed_when: false
      register: lib32_nvidia_utils_beta
      ignore_errors: true
    - name: Install nvidia-beta-dkms
      yay:
        name: nvidia-beta-dkms
        state: present
        update_cache: true
    - name: Install nvidia-utils-beta
      yay:
        name: nvidia-utils-beta
        state: present
        update_cache: true
      when: nvidia_utils_beta.stdout is not search('nvidia-utils-beta')
    - name: Install lib32-nvidia-utils-beta
      yay:
        name: nvidia-utils-beta
        state: present
        update_cache: true
      when: lib32_nvidia_utils_beta.stdout is not search('lib32-nvidia-utils-beta')
    - name: Setup modeset for nvidia-drm
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/nvidia.conf
        line: options nvidia-drm modeset=1 fbdev=1
        mode: "0644"
        create: true
        state: present
    - name: Add to mkinitcpio.conf
      ansible.builtin.lineinfile:
        path: /etc/mkinitcpio.conf
        regexp: "^MODULES=()"
        line: "MODULES=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)"
        state: present
    - name: Check if nvidia.NVreg_EnableGpuFirmware is present
      ansible.builtin.command:
        cmd: "grep ' nvidia.NVreg_EnableGpuFirmware=0' /etc/default/grub"
      register: nvidia_register
      changed_when: false
      ignore_errors: true
    - name: Add nvidia.NVreg_EnableGpuFirmware if not present (null register)
      ansible.builtin.command:
        cmd: "sudo sed -i 's/GRUB_CMDLINE_LINUX=\"\\(.*\\)\"/GRUB_CMDLINE_LINUX=\"\\1 nvidia.NVreg_EnableGpuFirmware=0\"/g' /etc/default/grub"
      when: nvidia_register.rc == 1  # Check if grep command exited with no matches (exit code 1)
      changed_when: false
    - name: Update GRUB
      ansible.builtin.command:
        cmd: grub-mkconfig -o /boot/grub/grub.cfg
      changed_when: false
